language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh

script:
  - ./build.sh

deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy.sh $TRAVIS_BRANCH $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on: development
  - provider: script
    script: ./deploy.sh $TRAVIS_BRANCH $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on: master