language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0

before_install:
- chmod +x build.sh
- chmod +x SonarScanner.MSBuild/sonar-scanner-3.2.0.1227/bin/sonar-scanner
- chmod a+x ./deploy.sh

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - dotnet restore PTZ.HomeManagement.sln

script:
  - ./build.sh $SONAR_TOKEN $TRAVIS_BRANCH

deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy.sh $TRAVIS_BRANCH $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on: development
  - provider: script
    script: ./deploy.sh latest $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on: master