version: '3.3'

services:
  PTZHMA-Worker:
    image: ptorrezao/ptz.homemanagement.worker:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_PROD}
      - DB_TYPE=PostgreSQL
      - MailGun_ApiKey=${MailGun_ApiKey}
      - MailGun_ApiBaseUri=${MailGun_ApiBaseUri}
      - MailGun_RequestUri=${MailGun_RequestUri}
      - MailGun_From=${MailGun_From}
      - MailGun_Domain=${MailGun_From}
    networks:
       - proxy
    depends_on:
     - db
 
  PTZHMA-Prod:
    image: ptorrezao/ptz.homemanagement:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT_PROD}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_PROD}
      - DB_TYPE=PostgreSQL
      - Sentry_DSN=${Sentry_DSN}
      - Sentry_IncludeRequestPayload=${Sentry_IncludeRequestPayload} 
      - Sentry_IncludeActivityData=${Sentry_IncludeActivityData} 
      - Sentry_MinimumBreadcrumbLevel=${Sentry_MinimumBreadcrumbLevel} 
      - Sentry_MinimumEventLevel=${Sentry_MinimumEventLevel}
      - MailGun_ApiKey=${MailGun_ApiKey}
      - MailGun_ApiBaseUri=${MailGun_ApiBaseUri}
      - MailGun_RequestUri=${MailGun_RequestUri}
      - MailGun_From=${MailGun_From}
      - MailGun_Domain=${MailGun_Domain}
    deploy:
      labels:
       - traefik.backend=[PTZHMA]-HomeManagement
       - traefik.frontend.rule=Host:${TOP_DOMAIN}
       - traefik.port=80
       - traefik.tags=HomeManagement,bla
      replicas: 1
    networks:
       - proxy
    depends_on:
     - db
     
  db:
    image: postgres:10
    restart: always
    networks:
       - proxy
    deploy:
     placement:
        constraints: [node.role == manager]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - DB_src:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
       - proxy
    deploy:
      labels:
       - traefik.backend=[PTZHMA]-Adminer
       - traefik.frontend.rule=Host:adminer.${TOP_DOMAIN}
       - traefik.port=8080
      replicas: 0
   
volumes:
  DB_src:

networks:
  proxy:
    external: true