version: '3.4'

services:
  ptz.homemanagement.worker:
    build:
      context: .
      dockerfile: PTZ.HomeManagement.Worker/Dockerfile
    image: ptorrezao/ptz.homemanagement.worker:build

  ptz.homemanagement:
    build:
      context: .
      dockerfile: PTZ.HomeManagement/Dockerfile
    image: ptorrezao/ptz.homemanagement:build
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=myverysecurepassword
      - DB_NAME=ptzhm
      - DB_TYPE=PostgreSQL
    external_links:
      - db:db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myverysecurepassword
      POSTGRES_USER: postgres
    ports:
      - "5432"

  adminer:
    image: adminer
    restart: always
    external_links:
      - db:db
    ports:
      - "8080"