version: '3.3'

services:
  PTZHMA:
    image: ptorrezao/ptz.homemanagement:${TAG}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_TYPE=PostgreSQL
      - Sentry_DSN=${Sentry_DSN}
      - Sentry_IncludeRequestPayload=${Sentry_IncludeRequestPayload} 
      - Sentry_IncludeActivityData=${Sentry_IncludeActivityData} 
      - Sentry_MinimumBreadcrumbLevel=${Sentry_MinimumBreadcrumbLevel} 
      - Sentry_MinimumEventLevel=${Sentry_MinimumEventLevel}
      - MailGun_ApiKey=${MailGun_ApiKey}
      - MailGun_ApiBaseUri=${MailGun_ApiBaseUri}
      - MailGun_RequestUri=${MailGun_RequestUri}
      - MailGun_From=${MailGun_From}
    deploy:
      replicas: 1
      labels:
       - traefik.backend=PTZHMA
       - traefik.frontend.rule=Host:ptzhma.${TOP_DOMAIN},${TOP_DOMAIN}
       - traefik.port=80
    networks:
       - proxy
    depends_on:
     - db
  
  db:
    image: postgres
    restart: always
    networks:
       - proxy
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - DB_src:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
       - proxy
    depends_on:
     - db
    deploy:
      replicas: 0
      labels:
       - traefik.backend=Adminer
       - traefik.frontend.rule=Host:adminer.${TOP_DOMAIN}
       - traefik.port=8080
      
volumes:
  DB_src:

networks:
  proxy:
    external: true