version: '3.3'

services:
  PTZHMA:
    image: ptorrezao/ptz.homemanagement:${TAG}
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIROMENT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_TYPE=CockroachDB
    deploy:
      labels:
       - traefik.backend=PTZHMA
       - traefik.frontend.rule=Host:ptzhma.${TOP_DOMAIN}
       - traefik.port=80
    networks:
       - proxy
    volumes:
      - PTZHM_src:/app
    depends_on:
     - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - DB_src:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
       - proxy
    deploy:
      labels:
       - traefik.backend=Adminer
       - traefik.frontend.rule=Host:adminer.${TOP_DOMAIN}
       - traefik.port=8080
      
volumes:
  PTZHM_src:
  DB_src:

networks:
  proxy:
    external: true